config/routes.rb
Railsbook::Application.routes.draw do
  resources :fun_comments

  resources :reviews

  resources :authors

  resources :users

  resources :books

  match ':controller(/:action(/:id))(.:format)'
end

app/models/fun_comment.rb
class FunComment < ActiveRecord::Base
  attr_accessible :author_no, :body, :deleted, :name
end

app/controllers/fun_comments_controller.rb
class FunCommentsController < ApplicationController
  # GET /fun_comments
  # GET /fun_comments.json
  def index
    @fun_comments = FunComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fun_comments }
    end
  end

  # GET /fun_comments/1
  # GET /fun_comments/1.json
  def show
    @fun_comment = FunComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fun_comment }
    end
  end

  # GET /fun_comments/new
  # GET /fun_comments/new.json
  def new
    @fun_comment = FunComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fun_comment }
    end
  end

  # GET /fun_comments/1/edit
  def edit
    @fun_comment = FunComment.find(params[:id])
  end

  # POST /fun_comments
  # POST /fun_comments.json
  def create
    @fun_comment = FunComment.new(params[:fun_comment])

    respond_to do |format|
      if @fun_comment.save
        format.html { redirect_to @fun_comment, notice: 'Fun comment was successfully created.' }
        format.json { render json: @fun_comment, status: :created, location: @fun_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @fun_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fun_comments/1
  # PUT /fun_comments/1.json
  def update
    @fun_comment = FunComment.find(params[:id])

    respond_to do |format|
      if @fun_comment.update_attributes(params[:fun_comment])
        format.html { redirect_to @fun_comment, notice: 'Fun comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fun_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fun_comments/1
  # DELETE /fun_comments/1.json
  def destroy
    @fun_comment = FunComment.find(params[:id])
    @fun_comment.destroy

    respond_to do |format|
      format.html { redirect_to fun_comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fun_comments_helper.rb
module FunCommentsHelper
end

app/views/fun_comments/_form.html.erb
<%= form_for(@fun_comment) do |f| %>
  <% if @fun_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fun_comment.errors.count, "error") %> prohibited this fun_comment from being saved:</h2>

      <ul>
      <% @fun_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_no %><br />
    <%= f.number_field :author_no %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fun_comments/edit.html.erb
<h1>Editing fun_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @fun_comment %> |
<%= link_to 'Back', fun_comments_path %>

app/views/fun_comments/index.html.erb
<h1>Listing fun_comments</h1>

<table>
  <tr>
    <th>Author no</th>
    <th>Name</th>
    <th>Body</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fun_comments.each do |fun_comment| %>
  <tr>
    <td><%= fun_comment.author_no %></td>
    <td><%= fun_comment.name %></td>
    <td><%= fun_comment.body %></td>
    <td><%= fun_comment.deleted %></td>
    <td><%= link_to 'Show', fun_comment %></td>
    <td><%= link_to 'Edit', edit_fun_comment_path(fun_comment) %></td>
    <td><%= link_to 'Destroy', fun_comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fun comment', new_fun_comment_path %>

app/views/fun_comments/new.html.erb
<h1>New fun_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', fun_comments_path %>

app/views/fun_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author no:</b>
  <%= @fun_comment.author_no %>
</p>

<p>
  <b>Name:</b>
  <%= @fun_comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @fun_comment.body %>
</p>

<p>
  <b>Deleted:</b>
  <%= @fun_comment.deleted %>
</p>


<%= link_to 'Edit', edit_fun_comment_path(@fun_comment) %> |
<%= link_to 'Back', fun_comments_path %>